steps:
  - label: "Jacoco Test Coverage"
    command: "bash scripts/unit-tests-coverage.sh"
    key: "generate-code-coverage"
    notify:
      - github_commit_status:
          context: "buildkite/code-coverage"
    artifact_paths:
      - "**/mockBuildDir/reports/jacoco/*/*.xml"

  - label: "Parse Jacoco Report"
    command: "bash scripts/jacocoXmlReportParser.sh"
    key: "code-coverage-report"
    depends_on:
      - step: "generate-code-coverage"
