steps:
  - label: "Jacoco Test Coverage"
    command: "bash scripts/unit-tests-coverage.sh"
    key: "code-coverage"
    notify:
      - github_commit_status:
          context: "buildkite/code-coverage"
